name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Get build dept.
      run: sudo apt install cmake qtbase5-dev libqt5svg5-dev qttools5-dev
    - name: Build it
      run: |
        cd PineapplePictures
        mkdir build
        cd build
        cmake ../
        make
        cpack
